services:
  jenkins_server:
    container_name: jenkins-server
    build:
      context: .
    restart: always
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    networks:
      - jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    privileged: true
    volumes:
      - ./jenkins-data:/var/jenkins_home:rw
      - ./jenkins-docker-certs:/certs/client:ro
networks:
  jenkins:
